Secret key generation + Play for cygwin

diff --git a/play b/play
--- a/play
+++ b/play
@@ -7,55 +7,65 @@
 # ~~~~~~~~~~~~~~~~~~~~~~ Utilities
 
 function absname {
-  unset return
-  if [ -d "$1" ] ; then   # Only a directory name.
-    dir="$1"
-    unset file
-  elif [ -f "$1" ] ; then # Strip off and save the filename.
-    dir=$(dirname "$1")
-    file="/"$(basename "$1")
-  else
-    echo "Error in absname ! ($1)"
-    # The file did not exist.
-    # Return null string as error.
-    return 1
-  fi
-
-  # Change to the directory and display the absolute pathname.
-  oldDir=$PWD
-  cd "$dir"  > /dev/null
-  return=${PWD}${file}
-  cd "$oldDir"  > /dev/null
+	unset return
+	if $CYGWIN; then
+		return=`cygpath -ma "$1"`
+	else	
+		if [ -d "$1" ] ; then   # Only a directory name.
+			dir="$1"
+			unset file
+		elif [ -f "$1" ] ; then # Strip off and save the filename.
+			dir=$(dirname "$1")
+			file="/"$(basename "$1")
+		else
+			echo "Error in absname ! ($1)"
+			return 1
+		fi	
+		# Change to the directory and display the absolute pathname.
+		oldDir=$PWD
+		cd "$dir"  > /dev/null
+		return=${PWD}${file}
+		cd "$oldDir"  > /dev/null
+	fi
 }
+
+
+# ~~~~~~~~~~~~~~~~~~~~~~ Is it a real OS ?
+
+CYGWIN=false
+case "`uname`" in
+	CYGWIN*) CYGWIN=true;;
+esac
 
 
 # ~~~~~~~~~~~~~~~~~~~~~~ Display usage
 
 function usage {
-    echo "~ Usage: play command [path or current directory] "
-    echo "~ "
-    echo "~ with,  new      Create a new application"                                
-    echo "~        run      Run the application in the current window"
-    echo "~        debug    Run the application under JDPA debugger"
-    echo "~        test     Run all tests"
-    echo "~        help     Show more commands"
-    echo "~"
+	echo "~ Usage: play command [path or current directory] "
+	echo "~ "
+	echo "~ with,  new      Create a new application"                                
+	echo "~        run      Run the application in the current window"
+	echo "~        debug    Run the application under JDPA debugger"
+	echo "~        test     Run all tests"
+	echo "~        help     Show more commands"
+	echo "~"
 }
 
 
 # ~~~~~~~~~~~~~~~~~~~~~~ Where is the framework ?
 
-absname "`dirname $0`"
+DIRNAME=`dirname "$0"`
+absname "$DIRNAME"
 PLAY_BASE="${return}"
 
 
 # ~~~~~~~~~~~~~~~~~~~~~~ Which is the framework id ?
 
 PLAY_ID=""
-if [ -f $PLAY_BASE/id ]; then    
-    PLAY_ID="`cat $PLAY_BASE/id`"
+if [ -f "$PLAY_BASE/id" ]; then    
+	PLAY_ID=`cat "$PLAY_BASE/id"`
 else
-	echo "" > $PLAY_BASE/id
+	echo "" > "$PLAY_BASE/id"
 fi
 
 
@@ -67,17 +77,23 @@ echo "~ | '_ \\| |/ _' | || |_|"
 echo "~ |  __/|_|\\____|\\__ (_)"
 echo "~ |_|            |__/   "
 echo "~"
+if [ ! -f "${PLAY_BASE}/framework/src/play/version" ]; then
+	echo "~ Oops. ${PLAY_BASE}/framework/src/play/version file not found"
+	echo "~ Is the framework compiled ?"
+	echo "~"
+	exit 1
+fi
 echo "~ play! `cat "${PLAY_BASE}/framework/src/play/version"`, http://www.playframework.org"
 if [ ! -z "$PLAY_ID" ]; then
-    echo "~ framework ID is $PLAY_ID"
+	echo "~ framework ID is $PLAY_ID"
 fi
 echo "~"
 
 
 # ~~~~~~~~~~~~~~~~~~~~~~ Which is the command ?
 if [ -z "$1" ]; then
-    usage
-    exit
+	usage
+	exit
 fi
 PLAY_COMMAND=$1
 
@@ -85,25 +101,25 @@ PLAY_COMMAND=$1
 # ~~~~~~~~~~~~~~~~~~~~~~ [help] Display help
 
 if [ "$PLAY_COMMAND" = "help" ] ; then
-    echo "~ Commands help : "
-    echo "~ "
-    echo "~        new          Create a new application"                                
-    echo "~        debug        Run the application under JDPA debugger"
-    echo "~        eclipsify    Create eclipse configuration files for this application"
-    echo "~        help         To show more commands"
-    echo "~        id           Define the framework ID"
-    echo "~        logs         Follow logs of the running application"
-    echo "~        netbeansify  Create netbeans configuration files for this application"
-    echo "~        pid          Display the pid of the running application"
-    echo "~        run          Run the application in the current window"
-    echo "~        start        Start the application in background"
-    echo "~        statistics   Display project statistics"
-    echo "~        stop         Stop the application"  
-    echo "~        test         Run all tests"
-    echo "~"
-    echo "~ Check full documentation at http://www.playframework.org/manual"
-    echo "~"
-    exit
+	echo "~ Commands help : "
+	echo "~ "
+	echo "~        new          Create a new application"                                
+	echo "~        debug        Run the application under JDPA debugger"
+	echo "~        eclipsify    Create eclipse configuration files for this application"
+	echo "~        help         To show more commands"
+	echo "~        id           Define the framework ID"
+	echo "~        netbeansify  Create netbeans configuration files for this application"
+	echo "~        out          Follow system.out of the running application"    
+	echo "~        pid          Display the pid of the running application"
+	echo "~        run          Run the application in the current window"
+	echo "~        start        Start the application in background"
+	echo "~        statistics   Display project statistics"
+	echo "~        stop         Stop the application"  
+	echo "~        test         Run all tests"
+	echo "~"
+	echo "~ Check full documentation at http://www.playframework.org/manual"
+	echo "~"
+	exit
 fi
 
 
@@ -117,12 +133,12 @@ if [ "$PLAY_COMMAND" = "id" ] ; then
     echo -n "~ What is the new framework ID (or blank to unset) ? "
     read id
     if [ -z $id ]; then
-        rm $PLAY_BASE/id
+        rm "$PLAY_BASE/id"
         echo "~"
         echo "~ Ok, the framework ID is unset"
         echo "~"
     else
-        echo $id > $PLAY_BASE/id
+        echo $id > "$PLAY_BASE/id"
         echo "~"
         echo "~ Ok, the framework ID is now $id"
         echo "~"
@@ -139,13 +155,13 @@ else
     APPLICATION_PATH="$2"
 fi
 if [ "$PLAY_COMMAND" = "new" ]; then
-    if [ -d $APPLICATION_PATH ]; then
-        absname $APPLICATION_PATH
+    if [ -d "$APPLICATION_PATH" ]; then
+        absname "$APPLICATION_PATH"
         echo "~ Oops. $return already exists"
         echo "~"
         exit 1
     else
-        mkdir $APPLICATION_PATH
+        mkdir "$APPLICATION_PATH"
     fi
 fi
 absname "$APPLICATION_PATH"
@@ -158,8 +174,15 @@ if [ "$PLAY_COMMAND" = "new" ] ; then
     echo "~ The new application will be created in ${APPLICATION_PATH}"
     echo -n "~ What is the application name ? "
     read applicationName 
-    cp -R ${PLAY_BASE}/resources/application-skel/* $APPLICATION_PATH
-    sed -e "s#%APPLICATION_NAME%#$applicationName#g" "$PLAY_BASE/resources/application-skel/conf/application.conf" > "$APPLICATION_PATH/conf/application.conf" 
+    cp -R "${PLAY_BASE}/resources/application-skel/"* "$APPLICATION_PATH"
+    sed -e "s#%APPLICATION_NAME%#$applicationName#g" "$PLAY_BASE/resources/application-skel/conf/application.conf" > "$APPLICATION_PATH/conf/application.conf.tmp" 
+    if $CYGWIN; then
+        SECRET_KEY=$RANDOM$RANDOM$RANDOM$RANDOM
+    else
+        SECRET_KEY=`dd if=/dev/random bs=1 count=32 2>/dev/null |xxd -c 256 -ps`
+    fi
+    sed -e "s#%SECRET_KEY%#$SECRET_KEY#g" "$APPLICATION_PATH/conf/application.conf.tmp" > "$APPLICATION_PATH/conf/application.conf" 
+    rm "$APPLICATION_PATH/conf/application.conf.tmp"
     echo "~"
     echo "~ Ok, the application is created."
     echo "~ Start it with : play run $2" 
@@ -188,16 +211,33 @@ fi
 
 # ~~~~~~~~~~~~~~~~~~~~~~ Build classpath
 
+AGENT_PATH="${PLAY_BASE}/framework/play.jar"
+
 CLASSPATH="$APPLICATION_PATH/conf/"
-CLASSPATH="$CLASSPATH:$PLAY_BASE/framework/play.jar"
+if $CYGWIN; then
+    CLASSPATH="$CLASSPATH;$PLAY_BASE/framework/play.jar"
+	OLD_IFS=$IFS
+	IFS=$'\n'
+fi
 for jar in `ls -c1 "$APPLICATION_PATH/lib"/*.jar 2> /dev/null`; do 
-    absname $jar    
-    CLASSPATH="$CLASSPATH:$return";
+    absname "$jar"  
+    if $CYGWIN; then
+    	CLASSPATH="$CLASSPATH;$return";
+	else
+    	CLASSPATH="$CLASSPATH:$return";
+    fi
 done
 for jar in `ls -c1 "$PLAY_BASE/framework/lib"/*.jar 2> /dev/null`; do 
-    absname $jar    
-    CLASSPATH="$CLASSPATH:$return";
+    absname "$jar"    
+    if $CYGWIN; then
+    	CLASSPATH="$CLASSPATH;$return";
+	else
+    	CLASSPATH="$CLASSPATH:$return";
+    fi
 done
+if $CYGWIN; then
+	IFS=OLD_IFS
+fi
 
 
 # ~~~~~~~~~~~~~~~~~~~~~~ [run] Run the application
@@ -205,7 +245,7 @@ done
 if [ "$PLAY_COMMAND" = "run" ] ; then
     echo "~ Ctrl+C to break"
     echo "~ "
-    "$JAVA_PATH" -javaagent:${PLAY_BASE}/framework/play.jar -classpath "$CLASSPATH" -Djava.endorsed.dirs="$PLAY_BASE/framework/endorsed" -Dapplication.path="${APPLICATION_PATH}" -Dplay.id=$PLAY_ID play.server.Server
+    "$JAVA_PATH" -javaagent:"$AGENT_PATH" -classpath "$CLASSPATH" -Djava.endorsed.dirs="$PLAY_BASE/framework/endorsed" -Dapplication.path="${APPLICATION_PATH}" -Dplay.id=$PLAY_ID play.server.Server
     echo 
     exit;
 fi
@@ -216,7 +256,7 @@ fi
 if [ "$PLAY_COMMAND" = "test" ] ; then
     echo "~ Running application tests"
     echo "~ "
-    "$JAVA_PATH" -javaagent:${PLAY_BASE}/framework/play.jar -classpath "$CLASSPATH" -Djava.endorsed.dirs="$PLAY_BASE/framework/endorsed" -Dapplication.path="${APPLICATION_PATH}" -Dplay.id=$PLAY_ID play.test.TestRunner
+    "$JAVA_PATH" -javaagent:"$AGENT_PATH" -classpath "$CLASSPATH" -Djava.endorsed.dirs="$PLAY_BASE/framework/endorsed" -Dapplication.path="${APPLICATION_PATH}" -Dplay.id=$PLAY_ID play.test.TestRunner
     echo 
     exit;
 fi
@@ -228,7 +268,7 @@ if [ "$PLAY_COMMAND" = "debug" ] ; then
     echo "~ Ctrl+C to break"
     echo "~ "
     echo -n "~ JPDA -> "
-    "$JAVA_PATH" -javaagent:${PLAY_BASE}/framework/play.jar -Xdebug -Xrunjdwp:transport=dt_socket,address=8000,server=y,suspend=n -Dplay.debug=yes -classpath "$CLASSPATH" -Djava.endorsed.dirs="$PLAY_BASE/framework/endorsed" -Dapplication.path="${APPLICATION_PATH}" -Dplay.id=$PLAY_ID  play.server.Server
+    "$JAVA_PATH" -javaagent:"$AGENT_PATH" -Xdebug -Xrunjdwp:transport=dt_socket,address=8000,server=y,suspend=n -Dplay.debug=yes -classpath "$CLASSPATH" -Djava.endorsed.dirs="$PLAY_BASE/framework/endorsed" -Dapplication.path="${APPLICATION_PATH}" -Dplay.id=$PLAY_ID  play.server.Server
     echo
     exit;
 fi
@@ -245,11 +285,11 @@ if [ "$PLAY_COMMAND" = "start" ] ; then
 	echo "~"
 	exit 1
     else
-	"$JAVA_PATH" -javaagent:${PLAY_BASE}/framework/play.jar -classpath "$CLASSPATH" -Djava.endorsed.dirs="$PLAY_BASE/framework/endorsed" -Dapplication.path="${APPLICATION_PATH}" -Dplay.id=$PLAY_ID  play.server.Server > "${APPLICATION_PATH}"/logs/system.out 2>&1 &
+	"$JAVA_PATH" -javaagent:"$AGENT_PATH" -classpath "$CLASSPATH" -Djava.endorsed.dirs="$PLAY_BASE/framework/endorsed" -Dapplication.path="${APPLICATION_PATH}" -Dplay.id=$PLAY_ID  play.server.Server > "${APPLICATION_PATH}"/logs/system.out 2>&1 &
 	echo "~ Ok, $APPLICATION_PATH is started"
 	echo "~ Output is redirected to ${APPLICATION_PATH}/logs/system.out ..."
-	echo $! > "${APPLICATION_PATH}/server.pid"
-        echo "~ The pid is `cat ${APPLICATION_PATH}/server.pid`"
+	echo $! > "$APPLICATION_PATH/server.pid"
+    echo "~ The pid is `cat "$APPLICATION_PATH"/server.pid`"
 	echo "~"
 	exit
     fi
@@ -261,7 +301,7 @@ fi
 
 if [ "$PLAY_COMMAND" = "stop" ] ; then
     if [ -f "${APPLICATION_PATH}/server.pid" ] ; then
-	echo "~ kill `cat ${APPLICATION_PATH}/server.pid`"	
+	echo "~ kill `cat "${APPLICATION_PATH}"/server.pid`"	
 	kill `cat "$APPLICATION_PATH/server.pid"`
 	rm "${APPLICATION_PATH}/server.pid"
 	rm "${APPLICATION_PATH}/logs/system.out"
@@ -280,7 +320,7 @@ fi
 
 if [ "$PLAY_COMMAND" = "pid" ] ; then
     if [ -f "${APPLICATION_PATH}/server.pid" ] ; then
-	echo "~ The pid for $APPLICATION_PATH is `cat ${APPLICATION_PATH}/server.pid`"
+	echo "~ The pid for $APPLICATION_PATH is `cat "${APPLICATION_PATH}/server.pid"`"
 	echo "~"
 	exit
     else
@@ -291,9 +331,9 @@ if [ "$PLAY_COMMAND" = "pid" ] ; then
 fi
 
 
-# ~~~~~~~~~~~~~~~~~~~~~~ [logs] Follow logs of the running application
+# ~~~~~~~~~~~~~~~~~~~~~~ [out] Follow logs of the running application
 
-if [ "$PLAY_COMMAND" = "logs" ] ; then
+if [ "$PLAY_COMMAND" = "out" ] ; then
     if [ -f "${APPLICATION_PATH}/server.pid" ] ; then
 	tail -f "${APPLICATION_PATH}/logs/system.out"
 	echo
@@ -310,7 +350,7 @@ fi
 
 if [ "$PLAY_COMMAND" = "restart" ] ; then
     if [ -f "${APPLICATION_PATH}/server.pid" ] ; then
-	echo "~ kill `cat ${APPLICATION_PATH}/server.pid`"	
+	echo "~ kill `cat "${APPLICATION_PATH}"/server.pid`"	
 	kill `cat "$APPLICATION_PATH/server.pid"`
 	rm "${APPLICATION_PATH}/server.pid"
 	rm "${APPLICATION_PATH}/logs/system.out"
@@ -320,11 +360,11 @@ if [ "$PLAY_COMMAND" = "restart" ] ; then
 	echo "~"
 	exit 1
     fi
-    "$JAVA_PATH" -javaagent:${PLAY_BASE}/framework/play.jar -classpath "$CLASSPATH" -Djava.endorsed.dirs="$PLAY_BASE/framework/endorsed" -Dapplication.path="${APPLICATION_PATH}" -Dplay.id=$PLAY_ID  play.server.Server > "${APPLICATION_PATH}"/logs/system.out 2>&1 &
+    "$JAVA_PATH" -javaagent:$AGENT_PATH -classpath "$CLASSPATH" -Djava.endorsed.dirs="$PLAY_BASE/framework/endorsed" -Dapplication.path="${APPLICATION_PATH}" -Dplay.id=$PLAY_ID  play.server.Server > "${APPLICATION_PATH}"/logs/system.out 2>&1 &
     echo "~ $APPLICATION_PATH is started"
     echo "~ Output is redirected to ${APPLICATION_PATH}/logs/system.out ..."
     echo $! > "${APPLICATION_PATH}/server.pid"
-    echo "~ The new pid is `cat ${APPLICATION_PATH}/server.pid`"
+    echo "~ The new pid is `cat "${APPLICATION_PATH}/server.pid"`"
     echo "~"
     exit
 fi
@@ -333,7 +373,7 @@ fi
 # ~~~~~~~~~~~~~~~~~~~~~~ [netbeansify] Create netbeans configuration files
 
 if [ "$PLAY_COMMAND" = "netbeansify" ] ; then
-    PROJECT_NAME="`cat $APPLICATION_PATH/conf/application.conf | grep application.name | sed -e 's/application.name=//g'`"	
+    PROJECT_NAME="`cat "$APPLICATION_PATH"/conf/application.conf | grep application.name | sed -e 's/application.name=//g'`"	
     rm -rf "$APPLICATION_PATH/nbproject"
     mkdir "$APPLICATION_PATH/nbproject"
     sed  -e "s|%APPLICATION_NAME%|$PROJECT_NAME|g" "$PLAY_BASE/resources/nbproject/project.xml" > "$APPLICATION_PATH/nbproject/project.xml.1.tmp" 
